services:
  # app:
  #   container_name: codyon-server
  #   build:
  #     context: ./
  #     dockerfile: dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - codyon-network
  #   depends_on:
  #     redis:
  #       condition: service_started
  #     db:
  #       condition: service_started
  #   env_file:
  #     - .example.env
  db:
    container_name: codyon-db
    image: postgres:16
    ports:
      - "5432:5432"
    networks:
      - codyon-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .example.env
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    container_name: codyon-redis
    image: redis:7
    networks:
      - codyon-network
    ports:
      - "6379:6379"

volumes:
  db_volume:
    name: codyon-db-volume

networks:
  codyon-network:
    name: codyon-network
    driver: bridge
