name: Codyon Server CI/CD

env:
  DOCKER_IMAGES: ghcr.io/${{ github.repository_owner }}/codyon-server

on:
  push:
    branches: [main]
    paths:
      - "src/*"
      - "docker*"
      - ".github/workflows/deploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.BUILDER }}
          password: ${{ secrets.BUILD_TOKEN }}
          logout: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGES }}
          tags: |
            latest
            ${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: deploy to ec2
        env:
          DOCKER_USERNAME: ${{ secrets.BUILDER }}
          DOCKER_PASSWORD: ${{ secrets.BUILD_TOKEN }}
        run: sh /etc/codyon/deploy.sh
