name: Codyon Server CI/CD

on:
  push:
    branches: [main]
    paths:
      - "src/*"
      - "docker*"
      - ".github/workflows/deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.BUILDER }}
          password: ${{ secrets.BUILD_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/codyon-server
          tags: |
            latest
            ${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io

      - name: deploy to ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          username: ubuntu
          port: 22
          script: sh /etc/codyon/deploy.sh
